//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.27 at 05:12:55 PM IST 
//


package com.mycardsolutions.webservice.soapdto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoginTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SSO"/&gt;
 *     &lt;enumeration value="OCEAN"/&gt;
 *     &lt;enumeration value="LDAP"/&gt;
 *     &lt;enumeration value="OCEANNLDAP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LoginTypeEnum", namespace = "SWSharedTypes")
@XmlEnum
public enum LoginTypeEnum {

    SSO,
    OCEAN,
    LDAP,
    OCEANNLDAP;

    public String value() {
        return name();
    }

    public static LoginTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
